apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: sjcprd-template-base
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 10.20.0.0/16
    services:
      cidrBlocks:
      - 10.21.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: AWSManagedControlPlane
    name: sjcprd-template-base-control-plane
  infrastructureRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: AWSManagedControlPlane
    name: sjcprd-template-base-control-plane
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: AWSManagedControlPlane
metadata:
  name: sjcprd-template-base-control-plane
spec:
  addons:
  - conflictResolution: overwrite
    name: vpc-cni
    version: v1.12.0-eksbuild.2
  - conflictResolution: overwrite
    name: coredns
    version: v1.8.7-eksbuild.3
  - conflictResolution: overwrite
    name: kube-proxy
    version: v1.24.9-eksbuild.1
  disableVPCCNI: false
  eksClusterName: sjcprd-template-base
  endpointAccess:
    private: true
    public: true
    publicCIDRs:
    - 0.0.0.0/0
  identityRef:
    kind: AWSClusterStaticIdentity
    name: 9dbf835bed844848acb0fa1ec17a0842-eks-for-product
  logging:
    apiServer: true
    audit: true
    authenticator: true
    controllerManager: true
    scheduler: true
  network:
    subnets:
    - availabilityZone: us-west-2a
      cidrBlock: 10.0.0.0/20
      isPublic: true
    - availabilityZone: us-west-2a
      cidrBlock: 10.0.128.0/20
      isPublic: false
    - availabilityZone: us-west-2b
      cidrBlock: 10.0.16.0/20
      isPublic: true
    - availabilityZone: us-west-2b
      cidrBlock: 10.0.144.0/20
      isPublic: false
  region: us-west-2
  sshKeyName: Pushkar-test
  version: v1.24
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  annotations: {}
  name: sjcprd-template-base-md-0
spec:
  clusterName: sjcprd-template-base
  replicas: 3
  selector:
    matchLabels:
      machineDeployment: sjcprd-template-base-md-0
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        machineDeployment: sjcprd-template-base-md-0
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: EKSConfigTemplate
          name: sjcprd-template-base-md-0
      clusterName: sjcprd-template-base
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AWSMachineTemplate
        name: sjcprd-template-base-md-0
      version: v1.24
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSMachineTemplate
metadata:
  name: sjcprd-template-base-md-0
spec:
  template:
    spec:
      ami: {}
      iamInstanceProfile: nodes.cluster-api-provider-aws.sigs.k8s.io
      instanceType: t2.medium
      sshKeyName: Pushkar-test
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: EKSConfigTemplate
metadata:
  name: sjcprd-template-base-md-0
spec:
  template:
    spec:
      apiRetryAttempts: 1500
---
apiVersion: sunpike.platform9.com/v1alpha2
kind: ClusterAddon
metadata:
  labels:
    clusterName: sjcprd-template-base
    sunpike.pf9.io/cluster: sjcprd-template-base
    type: pf9-profile-agent
  name: sjcprd-template-base-pf9-profile-agent
spec:
  override: {}
  type: pf9-profile-agent
  version: 2.0.1
  watch: true
---
apiVersion: sunpike.platform9.com/v1alpha2
kind: ClusterAddon
metadata:
  labels:
    clusterName: sjcprd-template-base
    sunpike.pf9.io/cluster: sjcprd-template-base
    type: metrics-server
  name: sjcprd-template-base-metrics-server
spec:
  override:
    params:
    - name: metricsCpuLimit
      value: 100m
    - name: metricsMemoryLimit
      value: 300Mi
  type: metrics-server
  version: 0.5.2
  watch: true
---
apiVersion: sunpike.platform9.com/v1alpha2
kind: ClusterAddon
metadata:
  labels:
    clusterName: sjcprd-template-base
    sunpike.pf9.io/cluster: sjcprd-template-base
    type: kubernetes-dashboard
  name: sjcprd-template-base-kubernetes-dashboard
spec:
  override: {}
  type: kubernetes-dashboard
  version: 2.4.0
  watch: true
---
apiVersion: sunpike.platform9.com/v1alpha2
kind: ClusterAddon
metadata:
  labels:
    clusterName: sjcprd-template-base
    sunpike.pf9.io/cluster: sjcprd-template-base
    type: monitoring
  name: sjcprd-template-base-monitoring
spec:
  override:
    params:
    - name: retentionTime
      value: 7d
  type: monitoring
  version: 0.57.1
  watch: true
