apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: sjcprd01-clusterTemplate
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 10.20.0.0/16
    services:
      cidrBlocks:
        - 10.21.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: NodeletControlPlane
    name: sjcprd01-clusterTemplate-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AWSCluster
    name: sjcprd01-clusterTemplate
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSCluster
metadata:
  name: sjcprd01-clusterTemplate
  namespace: default
spec:
  region: us-west-2
  sshKeyName: anmol-hybrid-dev
  identityRef:
    kind: AWSClusterStaticIdentity
    name: 9dbf835bed844848acb0fa1ec17a0842-aws-dev
  controlPlaneLoadBalancer:
    scheme: internet-facing
    crossZoneLoadBalancing: false
    healthCheckProtocol: TCP
  network:
    vpc:
      cidrBlock: 10.0.0.0/16
    subnets:
      - cidrBlock: 10.0.0.0/20
        isPublic: true
        availabilityZone: us-west-2a
      - cidrBlock: 10.0.128.0/20
        isPublic: false
        availabilityZone: us-west-2a
    cni:
      cniIngressRules:
        - description: bgp (calico)
          protocol: tcp
          fromPort: 179
          toPort: 179
        - description: IP-in-IP (calico)
          protocol: '4'
          fromPort: -1
          toPort: 65535
        - description: calico typha (pf9)
          protocol: tcp
          fromPort: 5473
          toPort: 5473
        - description: node exporter (pf9)
          protocol: tcp
          fromPort: 9100
          toPort: 9100
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: NodeletControlPlane
metadata:
  name: sjcprd01-clusterTemplate-control-plane
  namespace: default
spec:
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: AWSMachineTemplate
      name: sjcprd01-clusterTemplate-control-plane
    nodeletConfigSpec:
      httpProxy: {}
  replicas: 3
  version: 1.24.7-pmk.99
  cni:
    calico:
      IPIPMode: Always
      IPv4BlkSize: 26
      IPv4DetectionMethod: first-found
      MTUSize: 1440
      natOutgoing: true
  dns: {}
  schedulable: false
  apiserver:
    apiGroupsAndVersions: ''
    privileged: true
    extraArgs: {}
  etcdBackup:
    - name: daily
      target: local
      localPath: /etc/pf9/etcd-backup
      dailyBackupTime: '00:10'
      backupCount: 5
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSMachineTemplate
metadata:
  name: sjcprd01-clusterTemplate-control-plane
  namespace: default
spec:
  template:
    spec:
      publicIP: false
      rootVolume:
        size: 50
        type: gp3
      nonRootVolumes:
        - size: 100
          type: gp3
          deviceName: /dev/xvdb
      iamInstanceProfile: control-plane.cluster-api-provider-aws.sigs.k8s.io
      instanceType: t2.large
      sshKeyName: anmol-hybrid-dev
      ami:
        id: ami-041e1a7338bd36f08
      cloudInit:
        insecureSkipSecretsManager: true
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: sjcprd01-clusterTemplate-md-0
  namespace: default
  annotations: {}
spec:
  clusterName: sjcprd01-clusterTemplate
  replicas: 3
  selector:
    matchLabels:
      machineDeployment: sjcprd01-clusterTemplate-md-0
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        machineDeployment: sjcprd01-clusterTemplate-md-0
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: NodeletConfigTemplate
          name: sjcprd01-clusterTemplate-md-0
      clusterName: sjcprd01-clusterTemplate
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AWSMachineTemplate
        name: sjcprd01-clusterTemplate-md-0
      version: 1.24.7-pmk.99
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSMachineTemplate
metadata:
  name: sjcprd01-clusterTemplate-md-0
  namespace: default
spec:
  template:
    spec:
      rootVolume:
        size: 50
        type: gp3
      nonRootVolumes:
        - size: 100
          type: gp3
          deviceName: /dev/xvdb
      ami:
        id: ami-041e1a7338bd36f08
      iamInstanceProfile: nodes.cluster-api-provider-aws.sigs.k8s.io
      instanceType: t2.medium
      sshKeyName: anmol-hybrid-dev
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: NodeletConfigTemplate
metadata:
  name: sjcprd01-clusterTemplate-md-0
  namespace: default
spec:
  template:
    spec:
      labels: {}
      taints: []
---
apiVersion: sunpike.platform9.com/v1alpha2
kind: ClusterAddon
metadata:
  labels:
    sunpike.pf9.io/cluster: sjcprd01-clusterTemplate
    type: pf9-profile-agent
    clusterName: sjcprd01-clusterTemplate
  name: sjcprd01-clusterTemplate-pf9-profile-agent
  namespace: default
spec:
  override: {}
  type: pf9-profile-agent
  version: 2.0.1
  watch: true
---
apiVersion: sunpike.platform9.com/v1alpha2
kind: ClusterAddon
metadata:
  labels:
    sunpike.pf9.io/cluster: sjcprd01-clusterTemplate
    type: metrics-server
    clusterName: sjcprd01-clusterTemplate
  name: sjcprd01-clusterTemplate-metrics-server
  namespace: default
spec:
  override:
    params:
      - name: metricsCpuLimit
        value: 100m
      - name: metricsMemoryLimit
        value: 300Mi
  type: metrics-server
  version: 0.5.2
  watch: true
---
apiVersion: sunpike.platform9.com/v1alpha2
kind: ClusterAddon
metadata:
  labels:
    sunpike.pf9.io/cluster: sjcprd01-clusterTemplate
    type: kubernetes-dashboard
    clusterName: sjcprd01-clusterTemplate
  name: sjcprd01-clusterTemplate-kubernetes-dashboard
  namespace: default
spec:
  override: {}
  type: kubernetes-dashboard
  version: 2.4.0
  watch: true
---
apiVersion: sunpike.platform9.com/v1alpha2
kind: ClusterAddon
metadata:
  labels:
    sunpike.pf9.io/cluster: sjcprd01-clusterTemplate
    type: monitoring
    clusterName: sjcprd01-clusterTemplate
  name: sjcprd01-clusterTemplate-monitoring
  namespace: default
spec:
  override:
    params:
      - name: retentionTime
        value: 7d
  type: monitoring
  version: 0.57.1
  watch: true
---
apiVersion: sunpike.platform9.com/v1alpha2
kind: ClusterAddon
metadata:
  labels:
    sunpike.pf9.io/cluster: sjcprd01-clusterTemplate
    type: coredns
    clusterName: sjcprd01-clusterTemplate
  name: sjcprd01-clusterTemplate-coredns
  namespace: default
spec:
  override:
    params:
      - name: dnsMemoryLimit
        value: 170Mi
      - name: dnsDomain
        value: cluster.local
      - name: CoresPerReplica
        value: '256'
      - name: NodesPerReplica
        value: '16'
      - name: MinReplicas
        value: '1'
      - name: MaxReplicas
        value: '10'
      - name: PollPeriodSecs
        value: '300'
  type: coredns
  version: 1.8.6
  watch: true
